[profile.default]
src = "contracts"
script = "scripts"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
remappings = ["@selfxyz/contracts/=node_modules/@selfxyz/contracts/"]

[rpc_endpoints]
celo_sepolia = "${CELO_SEPOLIA_RPC_URL}"
