import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import  WalletProvider  from '@/providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nomis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletProvider>
          {children}
        </WalletProvider>
      </body>
    </html>
  )
}
